Repository vivid-money/elmslie, pull requests merged in 2021-07, with the labels that each got.

#31 Setup CI with GitHub actions
  .github/sh/parse_library_version.sh
  .github/sh/update_version_property.sh
  .github/sh/validate_github_token_format.sh
  .github/sh/validate_has_git_changes.sh
  .github/sh/validate_main_branch.sh
  .github/sh/validate_version_format.sh
  .github/sh/validate_version_increased.sh
  .github/workflows/codequality.yml
  .github/workflows/release.yml
  sh/release.sh
Labels: enhancement

#32 Implement automatic changelog generation
  .github/changelogconfig/configuration.json
  .github/workflows/release.yml
Labels: enhancement

#43 Fix using Switcher with Completables
  elmslie-core/src/main/java/vivid/money/elmslie/core/switcher/Switcher.kt
Labels: bug

#42 Update test & specify build tools version explicitly
  elmslie-samples/android-loader/build.gradle
  elmslie-samples/android-loader/src/main/java/vivid/money/elmslie/samples/android/loader/App.kt
  elmslie-samples/kotlin-calculator/src/main/java/vivid/money/elmslie/samples/calculator/Store.kt
  gradle/android-library.gradle
  gradle/dependencies.gradle
Labels: housekeeping

#33 Fix double start reporting issue
  elmslie-android/src/main/java/vivid/money/elmslie/android/logger/strategy/Crash.kt
  elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
Labels: bug

#23 [Concept] Compose sample
  README.md
  elmslie-compose/build.gradle
  elmslie-compose/src/main/AndroidManifest.xml
  elmslie-compose/src/main/java/vivid/money/elmslie/compose/EffectWithKey.kt
  elmslie-compose/src/main/java/vivid/money/elmslie/compose/ElmComponentActivity.kt
  elmslie-compose/src/main/java/vivid/money/elmslie/compose/ElmComponentFragment.kt
  elmslie-samples/compose-paging/build.gradle
  elmslie-samples/compose-paging/src/main/AndroidManifest.xml
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/elm/PagingActor.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/elm/PagingModels.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/elm/PagingReducer.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/elm/PagingStoreFactory.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/model/Item.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/model/Page.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/repository/FakeApi.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/repository/LoadedPages.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/repository/PagesCache.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/repository/PagingRepository.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/view/MainActivity.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/view/PagingFragment.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/view/PagingScreen.kt
  elmslie-samples/compose-paging/src/main/res/layout/activity_main.xml
  elmslie-samples/compose-paging/src/main/res/mipmap/ic_launcher.png
  elmslie-samples/compose-paging/src/main/res/values/strings.xml
  elmslie-samples/compose-paging/src/main/res/values/themes.xml
  gradle/dependencies.gradle
  settings.gradle
Labels: enhancement

#41 Update dependencies automatically with Release Hub Gradle Plugin
  .github/workflows/update_dependencies.yml
  build.gradle
  gradle/android-library.gradle
  gradle/dependencies.gradle
  gradle/detekt.gradle
  gradle/release-hub.gradle
Labels: enhancement
