Repository vivid-money/elmslie, pull requests merged in 2021-08, with the labels that each got.

#28 Fix plugin for code generation
  README.md
  elmslie-plugin/build.gradle
  elmslie-plugin/src/main/kotlin/vivid/money/elmslie/plugin/presentation/PresentationLayerAction.kt
  elmslie-plugin/src/main/kotlin/vivid/money/elmslie/plugin/presentation/views/CreatePresentationLayerDialog.kt
  elmslie-plugin/src/main/resources/META-INF/plugin.xml
  gradle/dependencies.gradle
Labels: bug, dependencies, plugin

#65 Setup dokka for documentation publishing
  build.gradle
  gradle/android-publishing.gradle
  gradle/dependencies.gradle
Labels: enhancement

#67 Send init event only once in store lifecycle
  elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmScreen.kt
Labels: bug

#66 Add constuctor with layout res id to base android classes
  elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmActivity.kt
  elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmFragment.kt
  elmslie-compose/src/main/java/vivid/money/elmslie/compose/ElmComponentActivity.kt
  elmslie-compose/src/main/java/vivid/money/elmslie/compose/ElmComponentFragment.kt
  elmslie-samples/android-loader/src/main/java/vivid/money/elmslie/samples/android/loader/MainActivity.kt
  elmslie-samples/compose-paging/src/main/java/vivid/money/elmslie/samples/android/compose/view/MainActivity.kt
Labels: enhancement

#69 Add child store chaining possibility
  elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
  elmslie-core/src/main/java/vivid/money/elmslie/core/store/Store.kt
  elmslie-core/src/test/java/vivid/money/elmslie/core/store/ElmStoreWithChildTest.kt
Labels: enhancement
